### ISSUE TITLE
[feat] 거래 도메인 기능 구현

### ISSUE THREAD

**Issue by limjihoon99** [beyond-sw-camp/be08-2nd-BanpoXii-Waruru#21]
## ✨ 구현 할 기능
- [ ] 매물 거래 내역 조회 기능
- [ ] 매물 거래 내역 수정 기능
- [ ] 매물 거래 취소 기능

<br>

### 📕 레퍼런스

**Comment by uzz99** [comment]
2734b82 코멘트 한번만 확인해주십쇼! 👍
